ALTER TABLE texts
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE cards
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN number TYPE VARCHAR,
    ALTER COLUMN holder TYPE VARCHAR,
    ALTER COLUMN expires_at TYPE VARCHAR,
    ALTER COLUMN cvv TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE secrets
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN login TYPE VARCHAR,
    ALTER COLUMN password TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE files
    ALTER COLUMN file_name TYPE VARCHAR,
    ALTER COLUMN file_hash TYPE VARCHAR,
    ALTER COLUMN storage_file_path TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE users
    ALTER COLUMN login TYPE VARCHAR,
    ALTER COLUMN password TYPE VARCHAR;

ALTER TABLE texts ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE texts_id_seq OWNED BY texts.id;
ALTER TABLE texts ALTER COLUMN id SET DEFAULT nextval('texts_id_seq');

ALTER TABLE cards ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE cards_id_seq OWNED BY cards.id;
ALTER TABLE cards ALTER COLUMN id SET DEFAULT nextval('cards_id_seq');

ALTER TABLE secrets ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE secrets_id_seq OWNED BY secrets.id;
ALTER TABLE secrets ALTER COLUMN id SET DEFAULT nextval('secrets_id_seq');

ALTER TABLE files ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE files_id_seq OWNED BY files.id;
ALTER TABLE files ALTER COLUMN id SET DEFAULT nextval('files_id_seq');

ALTER TABLE users ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE users_id_seq OWNED BY users.id;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

DROP INDEX idx_files_owner_name;
