ALTER TABLE users
    ALTER COLUMN login TYPE VARCHAR(64),
    ALTER COLUMN password TYPE VARCHAR(72);

ALTER TABLE files
    ALTER COLUMN file_name TYPE VARCHAR(255),
    ALTER COLUMN file_hash TYPE VARCHAR(32),
    ALTER COLUMN storage_file_path TYPE VARCHAR(512),
    ALTER COLUMN metadata TYPE VARCHAR(1024),
    ALTER COLUMN checksum TYPE VARCHAR(64);

ALTER TABLE secrets
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN login TYPE VARCHAR(255),
    ALTER COLUMN password TYPE VARCHAR(255),
    ALTER COLUMN metadata TYPE VARCHAR(1024),
    ALTER COLUMN checksum TYPE VARCHAR(64);

ALTER TABLE cards
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN number TYPE VARCHAR(32),
    ALTER COLUMN holder TYPE VARCHAR(128),
    ALTER COLUMN expires_at TYPE VARCHAR(16),
    ALTER COLUMN cvv TYPE VARCHAR(8),
    ALTER COLUMN metadata TYPE VARCHAR(1024),
    ALTER COLUMN checksum TYPE VARCHAR(64);

ALTER TABLE texts
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN metadata TYPE VARCHAR(1024),
    ALTER COLUMN checksum TYPE VARCHAR(64);
