ALTER TABLE texts
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE cards
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN number TYPE VARCHAR,
    ALTER COLUMN holder TYPE VARCHAR,
    ALTER COLUMN expires_at TYPE VARCHAR,
    ALTER COLUMN cvv TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE secrets
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN login TYPE VARCHAR,
    ALTER COLUMN password TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE files
    ALTER COLUMN file_name TYPE VARCHAR,
    ALTER COLUMN file_hash TYPE VARCHAR,
    ALTER COLUMN storage_file_path TYPE VARCHAR,
    ALTER COLUMN metadata TYPE VARCHAR,
    ALTER COLUMN checksum TYPE VARCHAR;

ALTER TABLE users
    ALTER COLUMN login TYPE VARCHAR,
    ALTER COLUMN password TYPE VARCHAR;
