// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scarypuppp/gophkeeper/internal/server/repository (interfaces: SecretRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_secret_repository.go -package=mocks . SecretRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/scarypuppp/gophkeeper/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretRepository is a mock of SecretRepository interface.
type MockSecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretRepositoryMockRecorder is the mock recorder for MockSecretRepository.
type MockSecretRepositoryMockRecorder struct {
	mock *MockSecretRepository
}

// NewMockSecretRepository creates a new mock instance.
func NewMockSecretRepository(ctrl *gomock.Controller) *MockSecretRepository {
	mock := &MockSecretRepository{ctrl: ctrl}
	mock.recorder = &MockSecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepository) EXPECT() *MockSecretRepositoryMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockSecretRepository) CreateSecret(ctx context.Context, secret entities.Secret) (*entities.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, secret)
	ret0, _ := ret[0].(*entities.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockSecretRepositoryMockRecorder) CreateSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockSecretRepository)(nil).CreateSecret), ctx, secret)
}

// DeleteSecret mocks base method.
func (m *MockSecretRepository) DeleteSecret(ctx context.Context, owner int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, owner, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretRepositoryMockRecorder) DeleteSecret(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretRepository)(nil).DeleteSecret), ctx, owner, name)
}

// GetByName mocks base method.
func (m *MockSecretRepository) GetByName(ctx context.Context, owner int64, name string) (*entities.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, owner, name)
	ret0, _ := ret[0].(*entities.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSecretRepositoryMockRecorder) GetByName(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSecretRepository)(nil).GetByName), ctx, owner, name)
}

// GetSecretsByOwner mocks base method.
func (m *MockSecretRepository) GetSecretsByOwner(ctx context.Context, owner int64) ([]entities.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretsByOwner", ctx, owner)
	ret0, _ := ret[0].([]entities.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretsByOwner indicates an expected call of GetSecretsByOwner.
func (mr *MockSecretRepositoryMockRecorder) GetSecretsByOwner(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretsByOwner", reflect.TypeOf((*MockSecretRepository)(nil).GetSecretsByOwner), ctx, owner)
}

// UpdateSecret mocks base method.
func (m *MockSecretRepository) UpdateSecret(ctx context.Context, secret entities.Secret) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, secret)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockSecretRepositoryMockRecorder) UpdateSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockSecretRepository)(nil).UpdateSecret), ctx, secret)
}
