// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scarypuppp/gophkeeper/internal/server/repository (interfaces: CardRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_card_repository.go -package=mocks . CardRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/scarypuppp/gophkeeper/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCardRepository is a mock of CardRepository interface.
type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
	isgomock struct{}
}

// MockCardRepositoryMockRecorder is the mock recorder for MockCardRepository.
type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

// NewMockCardRepository creates a new mock instance.
func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

// CreateCard mocks base method.
func (m *MockCardRepository) CreateCard(ctx context.Context, card entities.Card) (*entities.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCard", ctx, card)
	ret0, _ := ret[0].(*entities.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCard indicates an expected call of CreateCard.
func (mr *MockCardRepositoryMockRecorder) CreateCard(ctx, card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCard", reflect.TypeOf((*MockCardRepository)(nil).CreateCard), ctx, card)
}

// DeleteCard mocks base method.
func (m *MockCardRepository) DeleteCard(ctx context.Context, owner int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, owner, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockCardRepositoryMockRecorder) DeleteCard(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockCardRepository)(nil).DeleteCard), ctx, owner, name)
}

// GetByName mocks base method.
func (m *MockCardRepository) GetByName(ctx context.Context, owner int64, name string) (*entities.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, owner, name)
	ret0, _ := ret[0].(*entities.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCardRepositoryMockRecorder) GetByName(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCardRepository)(nil).GetByName), ctx, owner, name)
}

// GetCardsByOwner mocks base method.
func (m *MockCardRepository) GetCardsByOwner(ctx context.Context, owner int64) ([]entities.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardsByOwner", ctx, owner)
	ret0, _ := ret[0].([]entities.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardsByOwner indicates an expected call of GetCardsByOwner.
func (mr *MockCardRepositoryMockRecorder) GetCardsByOwner(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardsByOwner", reflect.TypeOf((*MockCardRepository)(nil).GetCardsByOwner), ctx, owner)
}

// UpdateCard mocks base method.
func (m *MockCardRepository) UpdateCard(ctx context.Context, card entities.Card) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCard", ctx, card)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCard indicates an expected call of UpdateCard.
func (mr *MockCardRepositoryMockRecorder) UpdateCard(ctx, card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCard", reflect.TypeOf((*MockCardRepository)(nil).UpdateCard), ctx, card)
}
