// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scarypuppp/gophkeeper/internal/server/repository (interfaces: UnitOfWork)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_unit_of_work.go -package=mocks . UnitOfWork
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/scarypuppp/gophkeeper/internal/server/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockUnitOfWork) BeginTx(ctx context.Context) (repository.UnitOfWork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(repository.UnitOfWork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockUnitOfWorkMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockUnitOfWork)(nil).BeginTx), ctx)
}

// Cards mocks base method.
func (m *MockUnitOfWork) Cards() repository.CardRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cards")
	ret0, _ := ret[0].(repository.CardRepository)
	return ret0
}

// Cards indicates an expected call of Cards.
func (mr *MockUnitOfWorkMockRecorder) Cards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cards", reflect.TypeOf((*MockUnitOfWork)(nil).Cards))
}

// Commit mocks base method.
func (m *MockUnitOfWork) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUnitOfWorkMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUnitOfWork)(nil).Commit), ctx)
}

// Files mocks base method.
func (m *MockUnitOfWork) Files() repository.FileRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files")
	ret0, _ := ret[0].(repository.FileRepository)
	return ret0
}

// Files indicates an expected call of Files.
func (mr *MockUnitOfWorkMockRecorder) Files() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockUnitOfWork)(nil).Files))
}

// Rollback mocks base method.
func (m *MockUnitOfWork) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUnitOfWorkMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUnitOfWork)(nil).Rollback), ctx)
}

// Secrets mocks base method.
func (m *MockUnitOfWork) Secrets() repository.SecretRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets")
	ret0, _ := ret[0].(repository.SecretRepository)
	return ret0
}

// Secrets indicates an expected call of Secrets.
func (mr *MockUnitOfWorkMockRecorder) Secrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockUnitOfWork)(nil).Secrets))
}

// Texts mocks base method.
func (m *MockUnitOfWork) Texts() repository.TextRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Texts")
	ret0, _ := ret[0].(repository.TextRepository)
	return ret0
}

// Texts indicates an expected call of Texts.
func (mr *MockUnitOfWorkMockRecorder) Texts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Texts", reflect.TypeOf((*MockUnitOfWork)(nil).Texts))
}

// Users mocks base method.
func (m *MockUnitOfWork) Users() repository.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(repository.UserRepository)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockUnitOfWorkMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockUnitOfWork)(nil).Users))
}
