// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scarypuppp/gophkeeper/internal/server/repository (interfaces: TextRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_text_repository.go -package=mocks . TextRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/scarypuppp/gophkeeper/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockTextRepository is a mock of TextRepository interface.
type MockTextRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTextRepositoryMockRecorder
	isgomock struct{}
}

// MockTextRepositoryMockRecorder is the mock recorder for MockTextRepository.
type MockTextRepositoryMockRecorder struct {
	mock *MockTextRepository
}

// NewMockTextRepository creates a new mock instance.
func NewMockTextRepository(ctrl *gomock.Controller) *MockTextRepository {
	mock := &MockTextRepository{ctrl: ctrl}
	mock.recorder = &MockTextRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextRepository) EXPECT() *MockTextRepositoryMockRecorder {
	return m.recorder
}

// CreateText mocks base method.
func (m *MockTextRepository) CreateText(ctx context.Context, text entities.Text) (*entities.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateText", ctx, text)
	ret0, _ := ret[0].(*entities.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateText indicates an expected call of CreateText.
func (mr *MockTextRepositoryMockRecorder) CreateText(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateText", reflect.TypeOf((*MockTextRepository)(nil).CreateText), ctx, text)
}

// DeleteText mocks base method.
func (m *MockTextRepository) DeleteText(ctx context.Context, owner int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteText", ctx, owner, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteText indicates an expected call of DeleteText.
func (mr *MockTextRepositoryMockRecorder) DeleteText(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteText", reflect.TypeOf((*MockTextRepository)(nil).DeleteText), ctx, owner, name)
}

// GetByName mocks base method.
func (m *MockTextRepository) GetByName(ctx context.Context, owner int64, name string) (*entities.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, owner, name)
	ret0, _ := ret[0].(*entities.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTextRepositoryMockRecorder) GetByName(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTextRepository)(nil).GetByName), ctx, owner, name)
}

// GetTextsByOwner mocks base method.
func (m *MockTextRepository) GetTextsByOwner(ctx context.Context, owner int64) ([]entities.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextsByOwner", ctx, owner)
	ret0, _ := ret[0].([]entities.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextsByOwner indicates an expected call of GetTextsByOwner.
func (mr *MockTextRepositoryMockRecorder) GetTextsByOwner(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextsByOwner", reflect.TypeOf((*MockTextRepository)(nil).GetTextsByOwner), ctx, owner)
}

// UpdateText mocks base method.
func (m *MockTextRepository) UpdateText(ctx context.Context, text entities.Text) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateText", ctx, text)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateText indicates an expected call of UpdateText.
func (mr *MockTextRepositoryMockRecorder) UpdateText(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateText", reflect.TypeOf((*MockTextRepository)(nil).UpdateText), ctx, text)
}
