// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scarypuppp/gophkeeper/internal/server/repository (interfaces: FileRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_file_repository.go -package=mocks . FileRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/scarypuppp/gophkeeper/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
	isgomock struct{}
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// CreateFile mocks base method.
func (m *MockFileRepository) CreateFile(ctx context.Context, file entities.File) (*entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", ctx, file)
	ret0, _ := ret[0].(*entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockFileRepositoryMockRecorder) CreateFile(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockFileRepository)(nil).CreateFile), ctx, file)
}

// DeleteFile mocks base method.
func (m *MockFileRepository) DeleteFile(ctx context.Context, owner int64, fileHash, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, owner, fileHash, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileRepositoryMockRecorder) DeleteFile(ctx, owner, fileHash, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileRepository)(nil).DeleteFile), ctx, owner, fileHash, fileName)
}

// GetByHashAndName mocks base method.
func (m *MockFileRepository) GetByHashAndName(ctx context.Context, owner int64, fileHash, fileName string) (*entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHashAndName", ctx, owner, fileHash, fileName)
	ret0, _ := ret[0].(*entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHashAndName indicates an expected call of GetByHashAndName.
func (mr *MockFileRepositoryMockRecorder) GetByHashAndName(ctx, owner, fileHash, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHashAndName", reflect.TypeOf((*MockFileRepository)(nil).GetByHashAndName), ctx, owner, fileHash, fileName)
}

// GetByName mocks base method.
func (m *MockFileRepository) GetByName(ctx context.Context, owner int64, fileHash string) (*entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, owner, fileHash)
	ret0, _ := ret[0].(*entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockFileRepositoryMockRecorder) GetByName(ctx, owner, fileHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockFileRepository)(nil).GetByName), ctx, owner, fileHash)
}

// GetFilesByOwner mocks base method.
func (m *MockFileRepository) GetFilesByOwner(ctx context.Context, owner int64) ([]entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesByOwner", ctx, owner)
	ret0, _ := ret[0].([]entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesByOwner indicates an expected call of GetFilesByOwner.
func (mr *MockFileRepositoryMockRecorder) GetFilesByOwner(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesByOwner", reflect.TypeOf((*MockFileRepository)(nil).GetFilesByOwner), ctx, owner)
}

// UpdateFileContent mocks base method.
func (m *MockFileRepository) UpdateFileContent(ctx context.Context, owner int64, fileHash, fileName, checksum string, size int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileContent", ctx, owner, fileHash, fileName, checksum, size)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFileContent indicates an expected call of UpdateFileContent.
func (mr *MockFileRepositoryMockRecorder) UpdateFileContent(ctx, owner, fileHash, fileName, checksum, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileContent", reflect.TypeOf((*MockFileRepository)(nil).UpdateFileContent), ctx, owner, fileHash, fileName, checksum, size)
}

// UpdateFileMetadata mocks base method.
func (m *MockFileRepository) UpdateFileMetadata(ctx context.Context, owner int64, fileHash, fileName, metadata string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileMetadata", ctx, owner, fileHash, fileName, metadata)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFileMetadata indicates an expected call of UpdateFileMetadata.
func (mr *MockFileRepositoryMockRecorder) UpdateFileMetadata(ctx, owner, fileHash, fileName, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileMetadata", reflect.TypeOf((*MockFileRepository)(nil).UpdateFileMetadata), ctx, owner, fileHash, fileName, metadata)
}
